### POST request to create patient
POST http://localhost:4000/patients
Content-Type: application/json

{
  "name": "Sachintha Bandara with billing account",
  "email": "test_billing_account@example.com",
  "address": "No 12 main street",
  "dateOfBirth": "1999-12-30",
  "registeredDate": "2025-06-16"
}
###